export const CREATE_BLOG_SUCCESS = "CREATE_BLOG_SUCCESS"
export const CREATE_BLOG_FAILURE = "CREATE_BLOG_FAILURE"

export const GET_BLOGS_SUCCESS = "GET_BLOGS_SUCCESS"
export const GET_BLOGS_FAILURE = "GET_BLOGS_FAILURE"

export const GET_BLOG_BY_ID_SUCCESS = "GET_BLOG_BY_ID_SUCCESS"
export const GET_BLOG_BY_ID_FAILURE = "GET_BLOG_BY_ID_FAILURE"

export const UPDATE_BLOG_SUCCESS = "UPDATE_BLOG_SUCCESS"
export const UPDATE_BLOG_FAILURE = "UPDATE_BLOG_FAILURE"

export const DELETE_BLOG_SUCCESS = "DELETE_BLOG_SUCCESS"
export const DELETE_BLOG_FAILURE = "DELETE_BLOG_FAILURE"

export const SAVE_OR_UNSAVE_BLOG_SUCCESS = "SAVE_OR_UNSAVE_BLOG_SUCCESS"
export const SAVE_OR_UNSAVE_BLOG_FAILURE = "SAVE_OR_UNSAVE_BLOG_FAILURE"

export const GET_BLOGS_SAVE_SUCCESS = "GET_BLOGS_SAVE_SUCCESS"
export const GET_BLOGS_SAVE_FAILURE = "GET_BLOGS_SAVE_FAILURE"





