export const REACTION_BLOG_SUCCESS = "REACTION_BLOG_SUCCESS"
export const REACTION_BLOG_FAILURE = "REACTION_BLOG_FAILURE"

export const UNREACTION_BLOG_SUCCESS = "UNLIKE_BLOG_SUCCESS"
export const UNREACTION_BLOG_FAILURE = "UNREACTION_BLOG_FAILURE"